set encoding=utf-8
scriptencoding utf-8

set nocompatible                       " be iMproved
filetype off                           " required!


" process all sub-configuration files
for filename in sort(split(glob('~/.vim/*.vim'), '\n'))
    execute 'source '.filename
endfor
