ZSH_THEME="rw2"

HISTFILE=${HOME}/.zsh_history
HISTSIZE=20000
SAVEHIST=20000

#  Disable Ctrl-D
set -o ignoreeof

setopt append_history
setopt extended_history
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt prompt_subst

unsetopt correctall


bindkey -e      # Use emacs key bindings           

autoload -Uz compinit
autoload -U history-search-end
compinit

zstyle ':completion:*' insert-tab pending
zstyle ':completion:*:manuals' separate-sections true

zstyle ':completion:*:*files' ignored-patterns '*?.o' '*?~'
zstyle ':completion:*:*cd:*' ignored-patterns '(*/|)(CVS|SCCS|SVN|GIT|HG)'
zstyle ':completion::*:(git|less|rm|emacs)' ignore-line true
zstyle ':completion:*' ignore-parents parent pwd
zstyle -d ':completion:*:hosts' hosts
zstyle ':completion:*:hosts' hosts $_ssh_hosts


# [Esc-w] - Kill from the cursor to the mark
bindkey '\ew' kill-region   
bindkey -s '\el' 'ls\n'      

# search history via exaxt prefix match
bindkey "\e[A"  history-beginning-search-backward-end
bindkey "\e[B"  history-beginning-search-forward-end
bindkey "OA" history-beginning-search-backward-end
bindkey "OB" history-beginning-search-forward-end

zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end


export LESS="-X ${LESS}"
# use vim as manpager
export MANPAGER="col -b | vim -c 'set ft=man ts=8 nomod nolist nu nonu noma' -c 'colo rich' -"


alias vi=vim

alias lsa='ls -lah'
alias l='ls -lah'
alias ll='ls -lh'
alias la='ls -lAh'

alias rake="noglob rake"
alias imix="iex -S mix"


#if (which tmux >/dev/null) && [[ -o login ]] &&  [[ -z "$TMUX" ]] && [[ -f ~/.dotfiles//scripts/tmux-login ]]; then
#  (tmux list-sessions 2>/dev/null | grep -q attached ) || exec zsh "$HOME/.dotfiles/scripts/tmux-login" $(which tmux)
#fi

[[ -f "${HOME}/.zshrc.os" ]]    && source "${HOME}/.zshrc.os"
[[ -f "${HOME}/.zshrc.host" ]]  && source "${HOME}/.zshrc.host"
[[ -f "${HOME}/.zshrc.local" ]] && source "${HOME}/.zshrc.local"

source "${HOME}/.dotfiles/lib/themes/${ZSH_THEME}.zsh-theme"

export PATH=./.bin:${HOME}/bin:${HOME}/.dotfiles/.bin:${PATH}

