#!/bin/sh

check_tab() {
    git diff-index -p --cached $against -- "$1" |
    grep -q $'^+\t' && echo "  $1"
}

# # Builtin whitespace checks.
# bad=$(git diff-index --check --cached $against --) || die "$bad"

bad=$(git diff-index --name-only --cached $against -- |
while read file; do
    check_tab "$file"
done)
test -z "$bad" || die 'Leading TABs added in
'"$bad"'
Convert them to spaces before commit.'
