#!/bin/sh

# https://stackoverflow.com/questions/53121208/git-dir-no-longer-set-in-pre-commit-hooks
GIT_DIR=${GIT_DIR-`git rev-parse --git-common-dir`}

die() {
    printf '\e[41;1m pre-commit hook failure \e[0m\n' 1>&2
    echo '-----------------------' 1>&2
    echo '' 1>&2
    printf "$@\n" 1>&2
    echo '' 1>&2
    echo '(you can always override this with `git commit -n`)'
    exit 1
}

#-----------------------------------------------------------------------------
# Check content that will be added by this commit.

if git rev-parse --verify -q HEAD > /dev/null; then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi


hook=$(basename $0)
for hook_plugin in $(ls -d -- ${GIT_DIR}/hooks/*/${hook}); do
    if [[ -x ${hook_plugin} ]]; then
        source ${hook_plugin}
    fi
done
