#!/bin/sh
#
# Copy or link this file as ".git/hooks/pre-commit".

die() {
    printf '\e[41;1m pre-commit hook failure \e[0m\n' 1>&2
    echo '-----------------------' 1>&2
    echo '' 1>&2
    printf "$@\n" 1>&2
    echo '' 1>&2
    echo '(you can always override this with `git commit -n`)'
    exit 1
}


#-----------------------------------------------------------------------------
# Check content that will be added by this commit.

if git rev-parse --verify -q HEAD > /dev/null; then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

#-----------------------------------------------------------------------------
# Disallow non-ascii file names.  The printable range starts at the
# space character and ends with tilde.
if test "$(git diff --cached --name-only --diff-filter=A -z $against |
       LC_ALL=C tr -d '[ -~]\0')"; then
    die 'Non-ascii file names may not be added:
'"$(git diff --cached --name-only --diff-filter=A $against)"
fi

#-----------------------------------------------------------------------------
# Builtin whitespace checks.
bad=$(git diff-index --check --cached $against --) || die "$bad"


#-----------------------------------------------------------------------------
# Reject leading TABs.
check_tab() {
    git diff-index -p --cached $against -- "$1" |
    grep -q $'^+\t' && echo "  $1"
}
bad=$(git diff-index --name-only --cached $against -- |
while read file; do
    check_tab "$file"
done)
test -z "$bad" || die 'Leading TABs added in
'"$bad"'
Convert them to spaces (2 per TAB) before commit.'
